language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"

notifications:
  email:
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#services-dev"
    use_notice: false
    skip_join: false

install:
  - make build

script:
  - make test
